[project]
name = "BioKG-Agents"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Ahmed Mohamed", email = "ahmed.h.h.mohamed@outlook.com"},
]
dependencies = ["openai>=1.6.0", "sentence-transformers>=2.2.2", "neo4j>=5.0.0", "pdfplumber>=0.10.0", "PyYAML>=6.0", "requests>=2.31.0"]
requires-python = "<3.14,>=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
